Restructure docs html to match https://segment.com/docs/ in structure
Shippable/docs pull request #48
Opened 2017-04-10 00:30 UTC by chetantarale

closes https://github.com/Shippable/docs/issues/9
closes https://github.com/Shippable/docs/issues/10

2017-04-10 04:45 UTC, rageshkrishna requested changes

2017-04-10 04:45 UTC, rageshkrishna commented on theme/saas/static/css/shippable.css
> +    height: calc(100vh - 63px)
What does this do?

2017-04-10 04:45 UTC, rageshkrishna commented on theme/saas/static/css/shippable.css
> +    font-size: 16px;
I think font sizes should be in relative units. Using pixels will not allow things to scale uniformly if we change the base font sizes. We need to be able to maintain the ratios across the board if we want to change the sizes later.

2017-04-10 04:45 UTC, rageshkrishna commented on theme/saas/static/css/shippable.css
> +    font-size: 16px;
Same as above; px sizing for fonts is a bad idea.

2017-04-10 04:45 UTC, rageshkrishna commented on theme/saas/static/css/shippable.css
> +    font-size: 16px;
Same as above; I think font sizes should be relative.

2017-04-10 04:45 UTC, rageshkrishna commented on theme/saas/static/css/shippable.css
> +    padding: 3rem 4rem 8rem 96px
I don't understand why everything is relative except the last one.

2017-04-10 04:46 UTC, rageshkrishna commented
There are a lot of "magic numbers" in the CSS. Is there a way to do things in a cleaner way?

2017-04-10 15:03 UTC, manishas commented
@chetantarale we spoke about the top nav yesterday but I still do not see it in this image.

2017-04-10 15:32 UTC, chetantarale commented
Updated  with latest image

2017-04-11 14:12 UTC, chetantarale commented
Merged this into a single PR to test the links. therefore closing this

2017-04-11 14:12 UTC, closed without merging